<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * 
 *
 * @package    local_bioauth
 * @copyright  Vinnie Monaco
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
 
global $keymap;
global $keycodes;
 
$keymap = array_combine(array(
    'UNKNOWN',
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
    'ENTER',
    'SPACE',
    'TAB',
    'ESCAPE',
    'BACKSPACE',
    'SHIFT',
    'CTRL',
    'ALT',
    'CAPS_LOCK',
    'NUM_LOCK',
    '0',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    'SEMICOLON',
    'EQUALS',
    'COMMA',
    'DASH',
    'PERIOD',
    'SLASH',
    'BACK_QUOTE',
    'OPEN_BRACKET',
    'BACK_SLASH',
    'CLOSE_BRACKET',
    'QUOTE',
    'LEFT',
    'UP',
    'RIGHT',
    'DOWN',
    'INSERT',
    'DELETE',
    'HOME',
    'END',
    'PAGE_UP',
    'PAGE_DOWN',
    'F1',
    'F2',
    'F3',
    'F4',
    'F5',
    'F6',
    'F7',
    'F8',
    'F9',
    'F10',
    'F11',
    'F12',
    'NUMPAD_0',
    'NUMPAD_1',
    'NUMPAD_2',
    'NUMPAD_3',
    'NUMPAD_4',
    'NUMPAD_5',
    'NUMPAD_6',
    'NUMPAD_7',
    'NUMPAD_8',
    'NUMPAD_9',
    'NUMPAD_MULTIPLY',
    'NUMPAD_ADD',
    'NUMPAD_SUBTRACT',
    'NUMPAD_DECIMAL',
    'NUMPAD_DIVIDE',
    'LEFT_WINDOWS',
    'RIGHT_WINDOWS',
    'LEFT_APPLE',
), range(0, 97));


$keycodes = array(
    'default' => array(
        65 => 'A',
        66 => 'B',
        67 => 'C',
        68 => 'D',
        69 => 'E',
        70 => 'F',
        71 => 'G',
        72 => 'H',
        73 => 'I',
        74 => 'J',
        75 => 'K',
        76 => 'L',
        77 => 'M',
        78 => 'N',
        79 => 'O',
        80 => 'P',
        81 => 'Q',
        82 => 'R',
        83 => 'S',
        84 => 'T',
        85 => 'U',
        86 => 'V',
        87 => 'W',
        88 => 'X',
        89 => 'Y',
        90 => 'Z',
        13 => 'ENTER',
        32 => 'SPACE',
        9 => 'TAB',
        27 => 'ESCAPE',
        8 => 'BACKSPACE',
        16 => 'SHIFT',
        17 => 'CTRL',
        18 => 'ALT',
        20 => 'CAPS_LOCK',
        144 => 'NUM_LOCK',
        48 => '0',
        49 => '1',
        50 => '2',
        51 => '3',
        52 => '4',
        53 => '5',
        54 => '6',
        55 => '7',
        56 => '8',
        57 => '9',
        59 => 'SEMICOLON',
        61 => 'EQUALS',
        188 => 'COMMA',
        189 => 'DASH',
        190 => 'PERIOD',
        191 => 'SLASH',
        192 => 'BACK_QUOTE',
        219 => 'OPEN_BRACKET',
        220 => 'BACK_SLASH',
        221 => 'CLOSE_BRACKET',
        222 => 'QUOTE',
        37 => 'LEFT',
        38 => 'UP',
        39 => 'RIGHT',
        40 => 'DOWN',
        45 => 'INSERT',
        46 => 'DELETE',
        36 => 'HOME',
        35 => 'END',
        33 => 'PAGE_UP',
        34 => 'PAGE_DOWN',
        112 => 'F1',
        113 => 'F2',
        114 => 'F3',
        115 => 'F4',
        116 => 'F5',
        117 => 'F6',
        118 => 'F7',
        119 => 'F8',
        120 => 'F9',
        121 => 'F10',
        122 => 'F11',
        123 => 'F12',
        96 => 'NUMPAD_0',
        97 => 'NUMPAD_1',
        98 => 'NUMPAD_2',
        99 => 'NUMPAD_3',
        100 => 'NUMPAD_4',
        101 => 'NUMPAD_5',
        102 => 'NUMPAD_6',
        103 => 'NUMPAD_7',
        104 => 'NUMPAD_8',
        105 => 'NUMPAD_9',
        106 => 'NUMPAD_MULTIPLY',
        107 => 'NUMPAD_ADD',
        109 => 'NUMPAD_SUBTRACT',
        110 => 'NUMPAD_DECIMAL',
        111 => 'NUMPAD_DIVIDE',
        91 => 'LEFT_WINDOWS',
        92 => 'RIGHT_WINDOWS',
        224 => 'LEFT_APPLE',
    ),

    'native' => array(
        10 => 'ENTER',
        24 => 'QUOTE',
        44 => 'COMMA',
        45 => 'DASH',
        46 => 'PERIOD',
        47 => 'SLASH',
        91 => 'OPEN_BRACKET',
        92 => 'BACK_SLASH',
        93 => 'CLOSE_BRACKET',
        155 => 'INSERT',
        127 => 'DELETE',
        524 => 'WINDOWS',
    ),

    'mozilla' => array(
    
    ),

);
